## Task 1 
Write a program that allows you to enter 4 numbers 
and stores them in a file called “Numbers”

In [12]:
my_file = open("Ilovedata.txt","w")

my_file.close()

In [14]:
my_file = open("Ilovedata.txt","w")

my_file.write (str("3, 45, 83, 21"))

my_file.close()

## Task 2
Write a program to ask a student for their percentage mark and convert this to a grade. The conversion will be done in a function called mark_grade

In [107]:
user_mark_grade=  int (input ("what is your % grade?"))
user_target_grade = int (input ("what is your % target grade?"))

In [108]:
print (user_mark_grade, user_target_grade)

50 80


In [118]:
value = user_mark_grade

In [119]:
def mark_grade (value):
    if value <30:
        result = "C"
    elif value <70:
        result = "B"
    else:
        result = "A"
    return result 
result = mark_grade(user_mark_grade)

In [120]:
if value < user_target_grade:
    print ("You need to study harder")
elif value > user_target_grade:
    print ("You did very well. Keep up the good work")
else:
    print ("Your just scraping it - work a little harder")

You need to study harder


In [ ]:
my_file = open("Ilovedata.txt", "w")

if mark_grade in range([1:30]):
    my_file.write(str("You need to work harder"))
    my_file.write("\n")

In [ ]:
for user_input_grade in range (len[1:33]):
    print ("You need to work a lot harder")
    
for i in range(len(my_1d_list)):
    print("The data at index location", i, "is:", my_1d_list[i])

## NUMPY 
1. Create a 1D array of numbers from 0 to 9
2. Create a 3×3 NumPy array of all Boolean value Trues
3. Extract all odd numbers from array of 1-10
4. Replace all odd numbers in an array of 1-10 with the value -1
5. Convert a 1D array to a 2D array with 2 rows
6. Create two arrays a and b, stack these two arrays vertically use the np.dot and 
np.sum to calculatetotals

In [ ]:
pip install numpy

In [11]:
import numpy as np


In [14]:
#1. Create a 1D array of numbers from 0 to 9
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ])

print(array1[0:10])

[0 1 2 3 4 5 6 7 8 9]


In [25]:
#2. Create a 3×3 NumPy array of all Boolean value Trues 

array2 = np.array([[True, True, True], [True, True, True], [True, True, True]])

print(array2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [27]:
#3. Extract all odd numbers from array of 1-10

array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ])
print(array1 [1:10:2])

[1 3 5 7 9]


In [34]:
# Replace all odd numbers in an array of 1-10 with the value -1
print(array1 [1:10:2] -1)

[0 2 4 6 8]


In [13]:
#Convert a 1D array to a 2D array with 2 rows
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

newArray1 = array1.reshape(2, 5) 

print(newArray1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:
# create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculatetotals
a = np.arange(1,10).reshape(3.3)
b = np.arange(10,19).reshape(3,3)


print(a)
print(b)


TypeError: 'builtin_function_or_method' object is not subscriptable